/**
 * InflaShield — shared TypeScript types
 *
 * All data shapes used across the application are defined here.
 * External API responses are validated with Zod in their respective
 * client modules before being cast to these types.
 */

// ---------------------------------------------------------------------------
// User input
// ---------------------------------------------------------------------------

export type RiskLevel = 'conservative' | 'balanced' | 'aggressive'

export interface HedgeRequest {
  /** ISO 4217 currency code — e.g. "NGN", "TRY", "ARS" */
  currency: string
  /** Savings amount in the user's local currency */
  amount: number
  riskLevel: RiskLevel
  /** Optional: user's preferred language for AI explanation (BCP 47) */
  locale?: string
}

// ---------------------------------------------------------------------------
// Exchange rate
// ---------------------------------------------------------------------------

export interface SpotRate {
  base: string
  target: string
  rate: number
  /** Unix timestamp of the rate */
  fetchedAt: number
}

// ---------------------------------------------------------------------------
// SoSoValue index data
// ---------------------------------------------------------------------------

export interface IndexComponent {
  symbol: string
  weight: number
}

export interface IndexRiskMetrics {
  volatility30d: number
  maxDrawdown90d: number
  sharpe30d: number | null
}

export interface SSIIndex {
  id: string
  name: string
  symbol: string
  tvlUsd: number
  components: IndexComponent[]
  return30d: number
  return7d: number
  riskMetrics: IndexRiskMetrics
}

export interface IndexPerformancePoint {
  date: string
  returnPct: number
  nav: number
}

export interface IndexPerformance {
  indexId: string
  window: '7d' | '30d' | '90d'
  dataPoints: IndexPerformancePoint[]
}

// ---------------------------------------------------------------------------
// Hedge engine
// ---------------------------------------------------------------------------

export interface IndexScore {
  index: SSIIndex
  /** 0–100 composite score */
  score: number
  /** Component breakdown */
  inflationCorrelation: number
  riskAdjustedReturn: number
  liquidityScore: number
}

export interface AllocationItem {
  indexId: string
  indexName: string
  indexSymbol: string
  /** Weight as a decimal: 0.6 = 60% */
  weight: number
  /** USD amount to allocate */
  amountUsd: number
}

export interface HedgeSignal {
  /** The currency the user is hedging against */
  currency: string
  /** User's savings converted to USD */
  amountUsd: number
  riskLevel: RiskLevel
  allocations: AllocationItem[]
  /** Scored rankings of all evaluated indices */
  indexScores: IndexScore[]
  /** Plain-English explanation — from AI if available, template otherwise */
  rationale: string
  /** True if rationale was generated by AI, false if template */
  rationaleIsAiGenerated: boolean
  generatedAt: string
}

// ---------------------------------------------------------------------------
// SoDEX execution
// ---------------------------------------------------------------------------

export type OrderStatus = 'submitted' | 'pending' | 'filled' | 'rejected' | 'cancelled'

export interface OrderRequest {
  indexId: string
  side: 'buy' | 'sell'
  amountUsd: number
  orderType: 'market' | 'limit'
  slippageTolerance?: number
  limitPrice?: number
}

export interface OrderResponse {
  orderId: string
  status: OrderStatus
  indexId: string
  amountUsd: number
  estimatedFillPrice: number | null
  createdAt: string
  txHash: string | null
}

export interface OrderFill {
  orderId: string
  status: 'filled' | 'rejected' | 'cancelled'
  filledAt: string | null
  fillPrice: number | null
  fillAmountUsd: number | null
  feeUsd: number | null
  rejectionReason: string | null
}

export interface ExecutionResult {
  signal: HedgeSignal
  orders: OrderResponse[]
}

// ---------------------------------------------------------------------------
// Portfolio (Phase 2)
// ---------------------------------------------------------------------------

export interface PortfolioPosition {
  indexId: string
  units: number
  valueUsd: number
  pnlUsd: number
  pnlPct: number
}

export interface Portfolio {
  totalValueUsd: number
  positions: PortfolioPosition[]
  fetchedAt: string
}

// ---------------------------------------------------------------------------
// Error handling
// ---------------------------------------------------------------------------

export type AppErrorCode =
  | 'RATE_UNAVAILABLE'
  | 'INDEX_FETCH_FAILED'
  | 'EXECUTION_FAILED'
  | 'AI_UNAVAILABLE'
  | 'INVALID_CURRENCY'
  | 'CONFIG_MISSING'

export interface AppError {
  code: AppErrorCode
  message: string
  retryable: boolean
}
